final-rc1

diff --git a/contrib/sfwg b/contrib/sfwg
--- a/contrib/sfwg
+++ b/contrib/sfwg
@@ -1,45 +1,44 @@
 #! /usr/bin/env bash
 
+# This script sets a WireGuard or Wiretap reverse tunnel on a target host.
 
-# This script sets a wireguard reverse tunnel on a target host.
+# X=<VERSION>-<PRIV>-<PUB>-<ENDPOINT>-<ALLOWED_IPS>
 
-# X=<VERSION>-<PRIV>-<PUB>-<ENDPOINT>-<DEV>-<IPV4Addr>-<IPV6Addr>
+# Test IPv6:
+# curl -I 'http://[2606:4700:4700::1111]'
+# ping6 2606:4700:4700::1111
 
-[[ -t 1 ]] && {
-# shellcheck disable=SC2034 # Unused
-CY="\e[1;33m" # yellow
-CG="\e[1;32m" # green
-CR="\e[1;31m" # red
-CC="\e[1;36m" # cyan
-# CM="\e[1;35m" # magenta
-# CW="\e[1;37m" # white
-CB="\e[1;34m" # blue
-CF="\e[2m"    # faint
-CN="\e[0m"    # none
-# CBG="\e[42;1m" # Background Green
-# night-mode
-CDR="\e[0;31m" # red
-CDG="\e[0;32m" # green
-CDY="\e[0;33m" # yellow
-CDB="\e[0;34m" # blue
-CDM="\e[0;35m" # magenta
-CDC="\e[0;36m" # cyan
-CUL="\e[4m"
+init_color()
+{
+    # shellcheck disable=SC2034 # Unused
+    CY="\e[1;33m" # yellow
+    CG="\e[1;32m" # green
+    CR="\e[1;31m" # red
+    CC="\e[1;36m" # cyan
+    # CM="\e[1;35m" # magenta
+    # CW="\e[1;37m" # white
+    CB="\e[1;34m" # blue
+    CF="\e[2m"    # faint
+    CN="\e[0m"    # none
+    # CBG="\e[42;1m" # Background Green
+    # night-mode
+    CDR="\e[0;31m" # red
+    CDG="\e[0;32m" # green
+    CDY="\e[0;33m" # yellow
+    CDB="\e[0;34m" # blue
+    CDM="\e[0;35m" # magenta
+    CDC="\e[0;36m" # cyan
+    CUL="\e[4m"
 }
 
-[[ -z $ADDRESS ]] && ADDRESS="192.168.0.1/32"
-[[ -z $ADDRES6 ]] && ADDRES6="fd::1/128"
-[[ -z $PEER_ADDRESS ]] && PEER_ADDRESS="192.168.0.0/29"
-[[ -z $PEER_ADDRES6 ]] && PEER_ADDRES6="fd::0/125"
+[[ -t 1 ]] && init_color
+
 [[ -z $WITHOUT_IPV6 ]] && WITH_IPV6=1
 [[ -z $WITHOUT_TUNE ]] && WITH_TUNE=1
 [[ -z $TYPE ]] && TYPE="wireguard:wiretap"
 [[ -z $UID ]] && UID=$(id -u)
 
-ERR()
-{
-	echo -e >&2 "[${CR}ERROR${CN}] $*"
-}
+ERR(){ echo -e >&2 "[${CR}ERROR${CN}] $*"; }
 
 ERREXIT()
 {
@@ -60,21 +59,48 @@ WARN()
 x2data()
 {
     local IFS
+    local str
+    local ip
+
     IFS="-"
     CONF=($X)
 
     [[ ${#CONF[@]} -lt  4 ]] && ERREXIT 255 "X= is not a valid configuration string."
-    [[ ${CONF[0]}  -ne  1 ]] && ERREXIT 255 "X= contains a bad verison number."
     [[ ${#CONF[1]} -ne 44 ]] && ERREXIT 255 "X= does not contain a valid private key."
     [[ ${#CONF[2]} -ne 44 ]] && ERREXIT 255 "X= does not contain a valid public key."
     
+    [[ -z $SF_VER ]] && SF_VER=${CONF[0]//[^0-9]}
     PRIV=${CONF[1]}
     PEER=${CONF[2]}
     EP=${CONF[3]}
 
-    [[ ${#CONF[@]} -ge 5 ]] && [[ -z $WG_DEV ]] && [[ ${#CONF[4]} -gt 1 ]] && WG_DEV=${CONF[4]}
-    [[ ${#CONF[@]} -ge 6 ]] && ADDRESS=${CONF[5]}
-    [[ ${#CONF[@]} -ge 7 ]] && ADDRES6=${CONF[6]}
+    [[ -z $SF_VER ]] && ERREXIT 255 "X= contains a bad version number."
+
+    str=${CONF[4]}
+    str="${str//[^0-9a-f,x:.\/]}"
+    [[ -n $str ]] && {
+        # Format: "172.16.0.x/16,fd:16::x/104"
+        ip=${str%%,*}
+        PEER_ADDRESS="${ip//x/0}"     # 172.16.0.0/16
+        ip=${ip%/*}
+        ADDRESS="${ip//x/1}/32"       # 172.16.0.0/32
+        # IPv6
+        ip=${str##*,}
+        PEER_ADDRES6="${ip//x/0}"     # fd:16::0/104
+        ip=${ip%/*}
+        ADDRES6="${ip//x/1}/128"      # fd:16::1/128
+    }
+
+    # [[ -z $ADDRESS ]] && ADDRESS="172.16.0.1/32"
+    # [[ -z $ADDRES6 ]] && ADDRES6="fd:16::1/128"
+    # [[ -z $PEER_ADDRESS ]] && PEER_ADDRESS="172.16.0.0/16"
+    # [[ -z $PEER_ADDRES6 ]] && PEER_ADDRES6="fd:16::0/104"
+
+    ### SF < 0.4.7 compatible
+    [[ -z $ADDRESS ]] && ADDRESS="192.168.0.1/32"
+    [[ -z $ADDRES6 ]] && ADDRES6="fd::1/128"
+    [[ -z $PEER_ADDRESS ]] && PEER_ADDRESS="192.168.0.0/16"
+    [[ -z $PEER_ADDRES6 ]] && PEER_ADDRES6="fd::0/104"
 }
 
 # Delete any IPT rule and add new one
@@ -160,14 +186,15 @@ wg_find_dev()
     }
 
     ### Check if it exists.
-    ip link show dev "${WG_DEV}" &>/dev/null && ERREXIT 255 "Device ${CDM}${WG_DEV}${CN} exists. Try ${CDC}ip link del ${WG_DEV}${CN} or ${CDC}export WG_DEV=Blah0${CN}"
+    ip link show dev "${WG_DEV}" &>/dev/null && ERREXIT 255 "Device ${CDM}${WG_DEV}${CN} exists.
+Try ${CDC}ip link del ${WG_DEV}${CN} or to use a different device try ${CDC}export WG_DEV=Blah0${CN}"
 }
 
 wg_up()
 {
     local fn
     local addr
-    command -v wg >/dev/null || ERREXIT 254 "WireGuard not installed.\nTry ${CDC}apt install wireguard${CN} or ${CDC}export TYPE=wiretap${CN} to force wiretap instead."
+    command -v wg >/dev/null || ERREXIT 254 "${CDM}WireGuard${CN} not installed.\nTry ${CDC}apt install wireguard${CN} or ${CDC}export TYPE=wiretap${CN} to force ${CDM}Wiretap${CN} instead."
     command -v sysctl >/dev/null || ERREXIT 255 "sysctl not found. Try ${CDC}apt-get install procps${CN}"
     command -v iptables >/dev/null || ERREXIT 255 "iptables not found. Try ${CDC}apt-get install iptables${CN}"
     command -v ip6tables >/dev/null || { WARN "ip6tables not found. Disabling IPv6". unset WITH_IPV6; }
@@ -190,7 +217,6 @@ wg_up()
     addr="${PEER_ADDRESS}"
     [[ -n $WITH_IPV6 ]] && addr+=",${PEER_ADDRES6}"
     # addr="0.0.0.0/0"
-    # [[ -n $WITH_IPV6 ]] && addr+=", ::/0"
     wg set "${WG_DEV}" private-key "${fn}" peer "$PEER" allowed-ips "${addr}" endpoint "${EP}" persistent-keepalive 25 || ERREXIT 255
     rm -f "${fn}"
 
@@ -218,7 +244,7 @@ wg_up()
     [[ -n $WITH_TUNE ]] && tune
 
     echo -e "\
-${CDG}SUCCESS${CN}
+${CDG}SUCCESS${CN} - ${CDM}WireGuard${CN} started.
 For status: ${CDC}wg show ${WG_DEV}${CN}
 To stop   : ${CDC}ip link del ${WG_DEV}${CN}
 Check the connection on your server:
@@ -230,27 +256,17 @@ wt_dl()
 {
     local arch
     local url
-    local os
 
     command -v tar >/dev/null || ERREXIT 255 "tar not found. Try ${CDC}apt install tar${CN}"
 
-    [[ -z $OSTYPE ]] && {
-        command -v uname >/dev/null || ERREXTI 255 "uname not found. Try ${CDC}apt install coreutils${CN}"
-        OSTYPE=$(uname -s)
-    }
-    OSTYPE="${OSTYPE,,}"
-
-    os="linux"
-    [[ $OSTYPE == *darwin* ]] && os="darwin"
-
     arch=$(uname -m)
-    url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_amd64.tar.gz"
+    url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${OS}_amd64.tar.gz"
     if [[ $arch == aarch64 ]] || [[ $arch == arm64 ]]; then
-        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_arm64.tar.gz"
+        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${OS}_arm64.tar.gz"
     elif [[ $arch == i686 ]] || [[ $arch == i386 ]]; then
-        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_386.tar.gz"
+        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${OS}_386.tar.gz"
     elif [[ $arch == *"armv"* ]]; then
-        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_armv6.tar.gz"
+        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${OS}_armv6.tar.gz"
     fi
 
     [[ -f wiretap ]] && rm -f wiretap
@@ -259,73 +275,145 @@ wt_dl()
         touch wiretap || ERREXIT 255 "Change to a writeable directory."
     }
     rm -f wiretap
-    echo -e "Downloading ${CDM}wiretap${CN}..."
+    echo -e "Downloading ${CDM}Wiretap${CN}..."
     IS_DOWNLOADED=1
     command -v curl >/dev/null && {
+        DL_CMD="curl -fsSL '$url' | tar xfvz - wiretap"
         curl -fsSL "$url" | tar xfz - wiretap && return
     }
 
     command -v wget >/dev/null && {
+        DL_CMD="wget -qO- '$url' | tar xfvz - wiretap"
         wget -qO- "$url" | tar xfz - wiretap && return
     }
     unset IS_DOWNLOADED
     [[ -f wiretap ]] && rm -f wiretap &>/dev/null # stale file
 
-    ERREXIT 255 "Failed to download Wiretap v0.2.1. Download it from
-${CDY}https://github.com/sandialabs/wiretap/releases${CN}
+    ERREXIT 255 "Failed to download ${CDM}Wiretap${CN}. Download it from
+${CDB}${CUL}https://github.com/sandialabs/wiretap/releases${CN}
 and start is manually:
     ${CDC}wiretap serve --private \"${PRIV}\" --public \"${PEER}\" --endpoint \"${EP}\"${CN}"
 }
 
+addenv()
+{
+    local varname
+    local value
+    varname=$1
+    value=$2
+
+    eval export "${varname}"="\$value"
+    ENVSTR+="${varname}='${value}' \\ "$'\n'
+}
+
 wt_up()
 {
-    local is_pidof
+    local is_has_pidof
     local err
+    local addr
+    local pid
+    local pidstr
+    local cmd_checkrunning
+    local arg
+    local n
+    local killname
 
-    command -v pidof >/dev/null && {
-        is_pidof=1
-        pids=$(pidof '[updated]') && ERREXIT 255 "Wiretap is already running with PID ${CDY}${pids}${CN}. Try ${CDC}killall wiretap${CN}"
+    [[ -z $OSTYPE ]] && {
+        command -v uname >/dev/null || ERREXTI 255 "uname not found. Try ${CDC}apt install coreutils${CN}"
+        OSTYPE=$(uname -s)
     }
+    OSTYPE="${OSTYPE,,}"
+    OS="linux"
+    [[ $OSTYPE == *darwin* ]] && OS="darwin"
 
-    command -v wiretap >/dev/null || {
-        PATH=".:$PATH"
-        [[ ! -e wiretap ]] && wt_dl
-    }
+    killname="wiretap"
+    cmd_checkrunning=()
+    CMD_PKILL="killall"
+    command -v pkill >/dev/null && CMD_PKILL="pkill"
+
+    if command -v pidof >/dev/null; then
+        is_has_pidof=1
+        cmd_checkrunning=("pidof" "[updated]")
+        pid=$(pidof '[updated]') && ERREXIT 255 "${CDM}Wiretap${CN} is already running with PID ${CDY}${pid}${CN}. To stop: ${CDC}${CMD_PKILL} '${killname}'${CN}"
+    elif command -v pkill >/dev/null; then
+        [[ $OS == "darwin" ]] && killname="\[updated\]"
+        cmd_checkrunning=("pkill" "-0" "${killname}")
+        "${cmd_checkrunning[@]}" && ERREXIT 255 "${CDM}Wiretap${CN} is already running. To stop: ${CDC}pkill '${killname}'${CN}"
+    elif command -v killall >/dev/null; then
+        cmd_checkrunning=("killall" "-0" "wiretap")
+        "${cmd_checkrunning[@]}" && ERREXIT 255 "${CDM}Wiretap${CN} is already running. To stop: ${CDC}killall '${killname}'${CN}"
+    fi
+        
+    # command -v wiretap >/dev/null || {
+    #     export PATH=".:$PATH"
+    #     [[ ! -e wiretap ]] && wt_dl
+    # }
+    if [[ -e wiretap ]]; then
+        echo -e "Using existing ${CDM}./wiretap${CN}"
+    else
+        wt_dl
+    fi
+    peer_addr="${PEER_ADDRESS}"
+    [[ -n $WITH_IPV6 ]] && peer_addr+=",${PEER_ADDRES6}"
+
     # CWD may have changed by wt_dl
+    # ./wiretap configure --simple
+    unset ENVSTR
+    if [[ $SF_VER -eq 1 ]]; then
+        addenv WIRETAP_INTERFACE_PRIVATEKEY "$PRIV"
+        addenv WIRETAP_PEER_PUBLICKEY "${PEER}"
+        addenv WIRETAP_PEER_ENDPOINT "${EP}"
+    else
+        addenv WIRETAP_RELAY_INTERFACE_PRIVATEKEY "${PRIV}"
+        addenv WIRETAP_RELAY_PEER_PUBLICKEY "${PEER}"
+        addenv WIRETAP_RELAY_PEER_ENDPOINT "${EP}"
+        addenv WIRETAP_SIMPLE "true"
+    fi
 
-    # WIRETAP_SIMPLE=true ./wiretap_linux_amd64 serve --ipv6-relay  fd::1 --allowed 192.168.0.1/28,fd::1/125
-    exec -a '[updated]' wiretap serve -q --private "${PRIV}" --public "${PEER}" --endpoint "${EP}" &>/dev/null &
-    [[ -n $is_pidof ]] && {
-        sleep 0.5
-        pid=$(pidof '[updated]') || {
-            err=1
+    if [[ -z $SF_DEBUG ]]; then
+        PATH=".:$PATH" exec -a '[updated]' wiretap serve -q --allowed "${peer_addr}" &>/dev/null &
+    else
+        PATH=".:$PATH" ./wiretap serve --allowed "${peer_addr}"
+    fi
+    [[ ${#cmd_checkrunning[@]} -gt 0 ]] && {
+        n=0
+        err=1
+        while [[ $n -lt 5 ]]; do
+            "${cmd_checkrunning[@]}" >/dev/null && { unset err; break; }
+            ((n++))
+            sleep 0.5
+        done
+        if [[ -z $err ]]; then
+            [[ -n $is_has_pidof ]] && pidstr=" with pid=${CDY}$(pidof '[updated]')${CN}"
+        else
             WARN "Failed to start wiretap."
-        }
+            echo -e "To run in the foreground:"
+            [[ -n $IS_DOWNLOADED ]] && echo -e "${CDC}${DL_CMD:-<download wiretap>}${CN}"
+            echo -e "${CDC}${ENVSTR}./wiretap serve --allowed '${peer_addr}'${CN}"
+        fi
     }
     
     [[ -n $IS_DOWNLOADED ]] && rm -f wiretap
     [[ -z $err ]] && echo -e "\
-${CDG}SUCCRSS${CN} - Started as ${CDY}[updated]${CN} with pid=${CDY}${pid:-pidof-not-found}${CN}
-To stop   : ${CDC}killall wiretap${CN}"
+${CDG}SUCCESS${CN} - ${CDM}Wiretap${CN} started as ${CDY}[updated]${CN}${pidstr} in the background.
+To stop   : ${CDC}${CMD_PKILL} '${killname}'${CN}"
 
-    echo -e "\
-To run in foreground:
-    1. ${CDC}killall wiretap${CN}
-    2. ${CDC}wiretap serve --private \"${PRIV}\" --public \"${PEER}\" --endpoint \"${EP}\"${CN}"
-
-    WARN "${CDM}Wiretap${CN} is ${CDR}not good${CN} for scanning. Consider using ${CDR}root${CN} instead."
+    # problem with gVisor DNAT & wt <=0.3.0 TCP mixup
+    WARN "${CDM}Wiretap${CN} is ${CDR}not good${CN} for scanning.
+Masscan: use ${CDC}-e wgExit --adapter-ip 172.16.0.3-172.16.128.2 --adapter-port 1024-33791${CN}
+Alternatively use ${CDM}WireGuard:${CDC}
+    ${CMD_PKILL} '${killname}'
+    export TYPE=wireguard
+    X=\"\$X\" bash -c \"\$(curl -fsSL thc.org/sfwg)\"${CN}"
 }
 
-[[ -z $X ]] && {
-    echo -e "\
-The variable ${CDY}X=${CN} is not set. Try
-    ${CDC}X=<YourConfigurationString> ./sfwg${CN}"
+[[ -z $X ]] && ERREXIT 255 "The variable ${CDY}X=${CN} is not set. Try
+    ${CDC}X=<YourConfigurationString> bash -c \"\$(curl -fsSL thc.org/sfwg)\"${CN}"
 
-    exit 255;
-}
 x2data
 
 [[ ${TYPE} == *wireguard* ]] && [[ $UID -eq 0 ]] && { wg_up; exit; }
 [[ ${TYPE} == *wiretap* ]] && { wt_up; exit; }
 
+[[ ${TYPE} == *wireguard* ]] && [[ $UID -ne 0 ]] && ERREXIT 255 "WireGuard requires root. Try ${CDC}exort TYPE=wiretap${CN} instead."
 ERREXIT 255 "Set ${CDM}export TYPE=wiretap${CN} or ${CDM}export TYPE=wireguard${CN}"
diff --git a/guest/fs-root/etc/shellrc b/guest/fs-root/etc/shellrc
--- a/guest/fs-root/etc/shellrc
+++ b/guest/fs-root/etc/shellrc
@@ -8,11 +8,6 @@ alias lt='ls -Alhrt'
 alias lss='ls -AlhrS'
 alias xterm='xterm-dark'
 
-function lsg {
-	[[ ! -t 1 ]] && { ls -Alh | grep -i -E "$*"; return; }
-	ls -Alh --color always | grep -i -E "$*" 
-}
-
 function dmesg {
 	[[ ! -t 1 ]] && { command curl -s rpc/dmesg/ -dnocolor=1; return; }
 	command curl -s rpc/dmesg/
@@ -28,6 +23,54 @@ alias ungron="gron --ungron"
 alias carbonyl="carbonyl --no-sandbox"
 alias seppuku="destruct"
 alias brave="brave-browser"
+
+# Warning for script kiddies
+[[ -t 0 ]] && [[ ! -e "${HOME}/.nokiddie" ]] && {
+	_nokiddie_warning()
+	{
+		local cmd
+		cmd="$1"
+		shift 1
+		local is_show
+		is_show=1
+
+		[[ -s "/config/self/wgname" ]] && unset is_show
+		[[ -e "${HOME}/.nokiddie" ]] && unset is_show
+		[[ -n $is_show ]] && {
+			echo -e >&2 "\
+${CDC}Massdns${CN}, ${CDC}Masscan${CN} et.al. do not work well via VPN providers. The uplink VPN providers
+and Google's 8.8.8.8 / 8.8.4.4 will ${CRY}block the requests${CN} when done to rapidly.
+Read how the pros do it: ${CB}${CUL}https://www.thc.org/segfault/faq/nokiddie${CN}"
+
+			if [[ -t 0 ]]; then
+				echo -e >&2 "${CDY}Continuing in 10 seconds. Press ENTER to continue now or CTRL-c to stop.${CN}"
+				read -r -t10
+			fi
+		}
+		command "$cmd" "$@"  # Might not exist and fail nicely here
+	}
+
+	command -v massdns    >/dev/null && massdns(){    _nokiddie_warning "massdns"    "$@"; }
+	command -v masscan    >/dev/null && masscan(){    _nokiddie_warning "masscan"    "$@"; }
+	command -v shuffledns >/dev/null && shuffledns(){ _nokiddie_warning "shuffledns" "$@"; }
+}
+
+### for 'curl -x socks5h://$(PROXY) ipinfo.io'
+TOR(){ echo "${SF_TOR_IP}:9050"; }
+PROXY()
+{
+	local IFS
+	local arr
+	local n
+
+	[[ ! -f /sf/share/proxies.txt ]] && { TOR; return; }
+	IFS=$'\n'
+	arr=($(<"/sf/share/proxies.txt"))
+	n=${#arr[@]}
+	RANDOM=$(date '+%N')
+	[[ ! $n -gt 0 ]] && { TOR; return; }
+	echo "${arr[$((RANDOM % n))]}"
+}
 
 [[ -n $IS_SHOW_MOTD_XPRA ]] && [[ -f /sf/bin/funcs_motd-xpra ]] && source /sf/bin/funcs_motd-xpra
 
@@ -146,7 +189,7 @@ tty -s && [[ -n $TERM ]] && [[ "$TERM" != dumb ]] && {
 	        		# 	command "$cmd" -- "$source" | source-highlight --failsafe -f esc --lang-def=changelog.lang --style-file=esc.style ;;
 			        *Makefile|*makefile)
 				        command "$cmd" -- "$source" | bat -pp -l Makefile ;;
-			        *.bashrc|*.zshrc|*.profile|*.bash_profile|*rc.local|*.shellrc)
+			        *.bashrc|*.zshrc|*.profile|*.bash_profile|*rc.local|*.shellrc|*_history)
 				        command "$cmd" -- "$source" | bat -pp -l bash ;;
 			        *)
 						ex="${source##*.}"
@@ -157,7 +200,8 @@ tty -s && [[ -n $TERM ]] && [[ "$TERM" != dumb ]] && {
 			    esac
 			done
 		}
-		alias cat="/usr/bin/bat -pp"
+		# alias cat="/usr/bin/bat -pp"
+		cat() { _hicmd cat "$@"; }
 		tail() { _hicmd tail "$@"; }
 		head() { _hicmd head "$@"; }
 	}
@@ -166,6 +210,12 @@ tty -s && [[ -n $TERM ]] && [[ "$TERM" != dumb ]] && {
 [[ -f /usr/bin/zoxide ]] && {
 	eval "$(zoxide init "$(basename "$SHELL")")"
 	alias cd='z'
+}
+
+# After 'alias ls=lsd...'
+function lsg {
+	[[ ! -t 1 ]] && { ls -Alh | grep -i -E "$*"; return; }
+	ls -Alh --color=always | grep -i -E "$*" 
 }
 
 [[ -f /usr/bin/fdfind ]] && alias fd=fdfind
@@ -195,6 +245,7 @@ tty -s && [[ -n $TERM ]] && [[ "$TERM" != dumb ]] && {
 [[ -z $VIRTUAL_ENV ]] && VIRTUAL_ENV="${SF_PRJ}"
 
 PATH="${HOME:-/sec/root}/go/bin:/sec/root/.local/bin:/sec/usr/sbin:/sec/usr/bin:/sf/bin:$PATH"
+[[ -d /usr/share/doc/python3-impacket/examples ]] && PATH="${PATH}:/usr/share/doc/python3-impacket/examples"
 
 _sf_info_non_perm()
 {
@@ -220,5 +271,5 @@ apt-get()
 }
 
 SHELLNAME="${SHELL##*/}"
-[[ -f "${HOME}/.gf/gs-completion.${SHELLNAME}" ]] && source "${HOME}/gf.gs-completion.${SHELLNAME}"
+[[ -f "${HOME}/.gf/gf-completion.${SHELLNAME}" ]] && source "${HOME}/.gf/gf-completion.${SHELLNAME}"
 unset SHELLNAME
diff --git a/master/cgi-bin/rpc b/master/cgi-bin/rpc
--- a/master/cgi-bin/rpc
+++ b/master/cgi-bin/rpc
@@ -4,6 +4,7 @@
 
 WG_PORT_MIN=32768
 WG_PORT_MAX=65535
+WT_VER=1
 COLOR="always"
 source /sf/bin/funcs.sh
 source /sf/bin/funcs_redis.sh
@@ -70,7 +71,6 @@ GetFormVars()
 	IFS=$ifs
 }
 
-
 # Load PID of WireGuard container
 load_config()
 {
@@ -97,18 +97,32 @@ net_print_example()
 	name="${1}"
 
 	echo -en "\
-To connect ${G}${name}${CN} use this command on the Exit Node:
-${C}X='1-${WT_PRIVATE}'
+To connect ${G}${name}${N} use this command on the Exit Node:
+${C}X='${WT_VER}-${WT_PRIVATE}'
 X+='-${WG_PUBLIC}'
-X+='-${WG_EP_HOST}:${WG_PORT}'
-X=\"\$X\" bash -c \"\$(curl -fsSL thc.org/sfwg)\"${CN}
+X+='-${WG_EP_HOST}:${WG_PORT}-${WG_IPS}'
+X=\"\$X\" bash -c \"\$(curl -fsSL thc.org/sfwg)\"${N}
  ---OR---
-${C}X='1-${WT_PRIVATE}'
+${C}X='${WT_VER}-${WT_PRIVATE}'
 X+='-${WG_PUBLIC}'
-X+='-${WG_EP_HOST}:${WG_PORT}'
-X=\"\$X\" bash -c \"\$(wget --no-verbose -O- thc.org/sfwg)\"${CN}
+X+='-${WG_EP_HOST}:${WG_PORT}-${WG_IPS}'
+X=\"\$X\" bash -c \"\$(wget --no-verbose -O- thc.org/sfwg)\"${N}
 "
 }
+
+
+net_print_commands()
+{
+	local name
+	name=$1
+	echo -en "\
+---
+Use ${C}curl rpc/net/down -d name=${name}${N} to disconnect.
+Use ${C}curl rpc/net/del  -d name=${name}${N} to delete the keys.
+Use ${Y}curl rpc/net/show${N} to check when the Exit Node ${G}${name}${N} has connected.
+"
+}
+
 
 cmd_net_list()
 {
@@ -256,7 +270,7 @@ mk_wt_name()
 		return
 	done
 
-	ERREXIT 255 "Could not find free name. Try -d name=<NAME>."
+	BAIL "Could not find free name. Try -d name=<NAME>." "RPC: could not find free name."
 }
 
 # rpc/net/init
@@ -373,11 +387,16 @@ net_down()
 
 	# Shut down WG interface
 	if [[ -z $name || $name == "all" ]]; then
+		### Need name for help below
+		[[ -e "${LID_WGNAME_FN}" ]] && name=$(<"${LID_WGNAME_FN}")
 		nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link delete group 31337 2>/dev/null || return
 	else
 		# Return early if device did not exist.
 		nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link delete "wg${name}" 2>/dev/null || return
 	fi
+	echo -e "${G}SUCCESS${N}"
+
+	echo -e "Use ${C}curl rpc/net/up -d name=${name:-<NAME>}${N} to connect again."
 	# Restore default routing
 	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add default via "${SF_NET_LG_ROUTER_IP}" || { echo "Oops. Could not set default route."; return; }
 	echo -e "${Y}WARNING${N}: All traffic exits via the DEFAULT ROUTE now."
@@ -429,19 +448,20 @@ cmd_net()
 cmd_net_show()
 {
 	local str
-	local dev
+	# local dev
 	local name
 	local is_not_connected
+	local now
 
-	dev="${WG_DEV:-all}"
+	# dev="${WG_DEV:-all}"
 	# [[ -n $R_WT_NAME ]] && dev="wg${R_WT_NAME}"
 
 	unset IFS
 	if [[ -z $COLOR ]]; then
-		str=$(nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n wg show "${dev}")
+		str=$(nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n wg show "${WG_DEV}")
 	else
 		# Use 'script' to force color output
-		str=$(script -q -c "nsenter.u1000 --setuid 0 --setgid 0 -t \"${PID}\" -n wg show \"${dev}\"" /dev/null </dev/null)
+		str=$(script -q -c "nsenter.u1000 --setuid 0 --setgid 0 -t \"${PID}\" -n wg show \"${WG_DEV}\"" /dev/null </dev/null)
 	fi
 	[[ -z $str ]] && {
 		echo -e "\
@@ -454,21 +474,33 @@ Use ${C}curl rpc/net/up${N} to enable a new Exit Node."
 	}
 
 	echo "$str"
-	[[ "$str" != *"latest handshake"* ]] && is_not_connected=1
+	if [[ "$str" == *"latest handshake"* ]]; then
+		str=$(nsenter.u1000 --setuid 0 --setgid 0 -t "$PID" -n wg show "${WG_DEV}" latest-handshakes)
+		str=${str##*$'\t'}
+		now=$(date +%s)
+		[[ $((now - str)) -gt 180 ]] && is_not_connected=1
+	else
+		is_not_connected=1
+	fi
 	[[ -e "${LID_WGNAME_FN}" ]] && {
 		name=$(<"${LID_WGNAME_FN}")
-		str="${CF}[${CDG}connected${CN}${CF}]${CN}"
-		[[ -n $is_not_connected ]] && str="${CF}[${CDR}EXIT Node not connected${CN}${CF}]${CN}"
-		echo -e "\n${CY}Name${CN}: ${CDY}${name:-UNKNOWN}${CN} ${str}"
+		str="${F}[${G}connected${N}${F}]${N}"
+		[[ -n $is_not_connected ]] && str="${F}[${N}${R}EXIT Node is not connected${N}${F}]${N}"
+		echo -e "\n${YY}Name${N}: ${Y}${name:-UNKNOWN}${N} ${str}"
+		### gvisor's DNAT used by WT is BROKEN
+		### https://github.com/sandialabs/wiretap/issues/18#issuecomment-1583106554
+		### Work-around it to iterate over as many src ports as possible.
+		[[ -z $is_not_connected ]] && echo -e "\
+${W}  peer${N}:  ${WG_IP_PRE}1, ${WG_IP6_PRE}1
+${W}  spoof${N}: ${WG_IP_PRE}3, ${WG_IP6_PRE}3 ${F}[masscan -e '${WG_DEV}' --adapter-ip ${WG_IP_PRE}3 --banners ...]${N}"
 	}
 	[[ -n $is_not_connected ]] && {
-		# echo -e "\n${Y}WARNING${N}: EXIT NODE NOT CONNECTED."
 		[[ -n $name ]] && {
 			load_wg "$name"
 			net_print_example "$name"
 		}
 	}
-	echo -e "Use ${C}curl rpc/net/down${N} to stop wireguard."
+	echo -e "\nUse ${C}curl rpc/net/down${N} to stop WireGuard."
 	exit
 }
 
@@ -523,6 +555,8 @@ GetFormVars
 	R=$CR
 	G=$CDG
 	M=$CDM
+	YY=$CY
+	W=$CW
 	N=$CN
 	F=$CF
 }
@@ -565,7 +599,18 @@ IFS=$_IFS
 	# CID="${arr[1]}"
 	PID="${arr[2]}"
 
-	# [[ -z $WG_DEV ]] && WG_DEV="wgExit"
+	[[ -z $WG_IPS ]] && WG_IPS="172.16.0.x/16,fd:16::x/104"
+
+	WG_IP_PRE="${WG_IPS%%x*}"      # 172.16.0.
+	WG_IP="${WG_IP_PRE}2/32"       # 172.16.0.2/32
+
+	WG_IP6_PRE="${WG_IPS##*,}"
+	WG_IP6_PRE="${WG_IP6_PRE%%x*}" # fd:16::
+	WG_IP6="${WG_IP6_PRE}2/128"    # fd:16::2/128
+
+	# dev="wg${WT_NAME}"
+	# Call Interface wgExit or user supplied. Previously we named wg${WT_NAME}.
+	[[ -z $WG_DEV ]] && WG_DEV="wgExit"
 
 	# Show current port configuration
 	[[ ${ARGS[0]} == 'net' && ${ARGS[1]} == 'show' ]] && cmd_net_show
@@ -587,22 +632,32 @@ IFS=$_IFS
 		exit
 	}
 
-	[[ -z $WT_NAME ]] || [[ ! -f "${LID_WGDIR}/wg-${WT_NAME}" ]] && {
+	if [[ -z $WT_NAME ]] && [[ -f "${LID_WGNAME_FN}" ]]; then
+		is_already_up=1
+		WT_NAME=$(<"${LID_WGNAME_FN}")
+	elif [[ -z $WT_NAME ]] || [[ ! -f "${LID_WGDIR}/wg-${WT_NAME}" ]]; then
 		# R_WT_NAME not supplied _or_ R_WT_NAME does not exist => Create new one.
 		net_init
 		net_init_print_info
-	}
+	fi
+
 	load_port
 	load_wg "${WT_NAME}"
 
-	# dev="wg${WT_NAME}"
-	# Call Interface wgExit or user supplied. Previously we named wg${WT_NAME}.
-	dev="${WG_DEV:-wgExit}"
+	[[ -n $is_already_up ]] && {
+		# HERE: No name supplied. Another WG is already UP. 
+		# nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip l sh "${WG_DEV}" &>/dev/null && {
+		name=$(<"${LID_WGNAME_FN}")
+		echo -e "${R}ERROR${N}: Exit Node ${G}${name}${N} is already UP."
+		net_print_example  "${name}"
+		net_print_commands "${name}"
+		exit 255
+	}
 
 	load_config
 
 	# Delete interface in WG namespace (should never happen):
-	nsenter -t "${WG_PID}" -n ip link del "${dev}" 2>/dev/null
+	nsenter -t "${WG_PID}" -n ip link del "${WG_DEV}" 2>/dev/null
 
 	# Delete all interface. Only allow ONE WG interface at a time.
 	# WireGuard only supports 1 private key per port number. Sharing the same
@@ -614,37 +669,39 @@ IFS=$_IFS
 	# _far_ more efficient.)
 	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link delete group 31337 2>/dev/null
 
-	err=$(nsenter -t "${WG_PID}" -n ip link add "${dev}" type wireguard 2>&1) || BAIL "${R}ERROR${N}: Failed: ip link add $dev (${err:0:32})." "Failed $dev" ": $err"
-	nsenter -t "${WG_PID}" -n ip link set "${dev}" group 31337 || BAIL "${R}ERROR${N}: ip link set FAILED."
+	err=$(nsenter -t "${WG_PID}" -n ip link add "${WG_DEV}" type wireguard 2>&1) || BAIL "${R}ERROR${N}: Failed: ip link add ${WG_DEV} (${err:0:32})." "Failed ${WG_DEV}" ": $err"
+	nsenter -t "${WG_PID}" -n ip link set "${WG_DEV}" group 31337 || BAIL "${R}ERROR${N}: ip link set FAILED."
 	echo "$WG_PRIVATE" >/dev/shm/private.$$
-	err=$(nsenter -t "${WG_PID}" -n wg set "${dev}" listen-port "${WG_PORT}" private-key "/dev/shm/private.$$" peer "${WT_PUBLIC}" allowed-ips 0.0.0.0/0,::/0 2>&1) || BAIL "${R}ERROR${N}: Failed: wg set (${err:0:128})"
+	err=$(nsenter -t "${WG_PID}" -n wg set "${WG_DEV}" listen-port "${WG_PORT}" private-key "/dev/shm/private.$$" peer "${WT_PUBLIC}" allowed-ips 0.0.0.0/0,::/0 2>&1) || BAIL "${R}ERROR${N}: Failed: wg set (${err:0:128})"
 	rm -f /dev/shm/private.$$
 	# Move Interface to user's container:
-	err=$(nsenter -t "${WG_PID}" -n ip link set "${dev}" netns "${PID}" 2>&1) || BAIL "${R}ERROR${N}: Failed to move $dev." "Failed $dev netns $PID" ": $err"
+	err=$(nsenter -t "${WG_PID}" -n ip link set "${WG_DEV}" netns "${PID}" 2>&1) || BAIL "${R}ERROR${N}: Failed to move ${WG_DEV}." "Failed ${WG_DEV} netns $PID" ": $err"
 
 	# Configure interface after moving
-	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -4 address add 192.168.0.2/32 dev "${dev}"
-	err=$(nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -6 address add fd::2/128 dev "${dev}" 2>&1) || echo >&2 "${CR}ERROR${CN}: ip -6: $err"
-	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link set mtu 1420 up dev "${dev}"
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -4 address add "${WG_IP}" dev "${WG_DEV}"
+	err=$(nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -6 address add "${WG_IP6}" dev "${WG_DEV}" 2>&1) || echo >&2 "${CR}ERROR${CN}: ip -6: $err"
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link set mtu 1420 up dev "${WG_DEV}"
 
 	# Add static routes for RPC
 	# nsenter -t "${PID}" -n ip route add "${SF_PC_IP}/32" dev eth0 # NOT NEEDED: RPC is on same network
 	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add "${SF_TOR_IP}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
 	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add "${SF_NET_ONION}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
 	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add "${SF_DNS}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
+	[[ -n $SF_MULLVAD_ROUTE ]] && nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add "${SF_MULLVAD_ROUTE}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
 	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route del default 2>/dev/null
-	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add default dev "${dev}"
-	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -6 route add default dev "${dev}"
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add default dev "${WG_DEV}"
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -6 route add default dev "${WG_DEV}"
+
+	# Packets to 172.16.0.3 should not be forwarded back to 172.16.0.3
+	# Can not use 'sysctl net.ipv4.conf.wgExit.forwarding=1' because /proc is mounted ro
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n iptables  -I FORWARD -i "${WG_DEV}" -j DROP
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip6tables -I FORWARD -i "${WG_DEV}" -j DROP
 
 	echo "${WT_NAME}" >"${LID_WGNAME_FN}"
 	echo "(%F{yellow}EXIT:%B${WT_NAME}%b%F{%(#.blue.green)})" >"${LID_PROMPT_FN}"
 	echo -e "${G}SUCCESS${N}"
-	net_print_example "${WT_NAME}"
-
-	echo "---"
-	echo -e "Use ${C}curl rpc/net/down -d name=${WT_NAME}${N} to disconnect."
-	echo -e "Use ${C}curl rpc/net/del  -d name=${WT_NAME}${N} to delete the keys."
-	echo -e "Use ${Y}curl rpc/net/show${N} to check when the Exit Node '${WT_NAME}' has connected."
+	net_print_example  "${WT_NAME}"
+	net_print_commands "${WT_NAME}"
 
 	exit
 }
