redis-support

diff --git a/host/fs-root/bin/segfaultsh b/host/fs-root/bin/segfaultsh
--- a/host/fs-root/bin/segfaultsh
+++ b/host/fs-root/bin/segfaultsh
@@ -115,7 +115,7 @@ tofile()
 	# Replace ' with '"'"'
 	str="${1//\'/\'\"\'\"\'}"
 	# [[ -n $SF_DEBUG ]] && ls -al $(dirname $2)
-	bash -c "echo '$str' >'$2' 2>/dev/null" || ERREXIT 231 "tofile: Failed to create "$(basename "$2")""
+	bash -c "echo '$str' >'$2' 2>/dev/null"
 }
 
 # Set $1 to $2 if $1 is not already set.
@@ -176,6 +176,7 @@ init_emu()
 
 	# Overwrite defaults to run in EMULATOR
 	SF_CFG_GUEST_DIR="${SF_EMU_DIR}/config-for-guest"
+	SF_GUEST_SELFDIR="${SF_EMU_DIR}/self-for-guest"
 	SF_ENCFS_SEC_DIR="${SF_EMU_DIR}/encfs-sec"
 
 	xmkdir "${SF_ENCFS_SEC_DIR}"
@@ -202,6 +203,7 @@ init_defaults()
 	SF_CONFIG_DIR="/config/host"
 	SF_ETCSF_DIR="/config/host/etc/sf"
 	SF_CFG_GUEST_DIR="${SF_SHMDIR}/config-for-guest" # Mounted to /config/guest
+	SF_GUEST_SELFDIR="${SF_SHMDIR}/self-for-guest"    # Mounted to /config/self
 	SF_ENCFS_SEC_DIR="${SF_SHMDIR}/encfs-sec"
 }
 
@@ -211,19 +213,35 @@ init_vars()
 	init_emu
 
 	NOW="$(date +%s)"
-	YOURIP="${SSH_CONNECTION%%[[:space:]]*}"
-	[[ -z $YOURIP ]] && ERREXIT 255 "SSH_CONNECTION= is is not set. segfaultsh not started via sshd?"
+	YOUR_IP="${SSH_CONNECTION%%[[:space:]]*}"
+	[[ -z $YOUR_IP ]] && ERREXIT 255 "SSH_CONNECTION= is is not set. segfaultsh not started via sshd?"
 	# Do not store IP addresses. Hash it with a secret (SEED) instead.
 	local str
-	str="$(echo "IP-${YOURIP}-${SF_SEED}" | sha512sum)"
-	YOURIP_HASH="${str:0:16}"
-	[[ -z $YOURIP_HASH ]] && ERREXIT 2 "YOURIP_HASH= not set"
+	str="$(echo -n "IP-${YOUR_IP}-${SF_SEED}" | sha512sum)"
+	YOUR_IP_HASH="${str:0:16}"
+	[[ -z $YOUR_IP_HASH ]] && ERREXIT 2 "YOUR_IP_HASH= not set"
 
 	[[ -z $SF_FQDN ]] && SF_FQDN="this"
 	DB_DIR="${SF_CONFIG_DIR}/db"
 	SF_USER_DB_DIR="${SF_CONFIG_DIR}/db/db-${LID}"
+
+	# DEBUGF "SF_REDIS_AUTH=${SF_REDIS_AUTH}"
 }
 
+mk_portforward()
+{
+	local ipport
+
+	ipport=$(echo -e "DEL portd:response-${LID}\"\n\
+RPUSH portd:blcmd \"getport ${LID}\"\n\
+BLPOP portd:response-${LID} 5" | REDISCLI_AUTH="${SF_REDIS_AUTH}" redis-cli --raw -h sf-redis) || return
+	DEBUGF "ipport='$ipport'"
+	ipport="${ipport##*$'\n'}"
+	[[ ! "${ipport##*:}" -gt 0 ]] && { DEBUGF "Failed to set up Reverse Port Forward (ipport='$ipport')"; return; }
+
+	# The PortD add's a /sf/run/self/reverse_forward.
+	DEBUGF "Reverse Port Forward: $ipport"
+}
 
 # Called when a new server is created.
 print_disclaimer()
@@ -268,14 +286,13 @@ print_goodbye()
 	# Restricted shell (-r) wont let us redirect stderr - use a bash-exec trick
 	n="$(bash -c "docker exec \"lg-${LID}\" pgrep . 2>/dev/null|wc -l")"
 	DEBUGF "Processes running: $n"
-	if [[ "$n" -gt 3 ]]; then
-		echo -e "Number of processes running: ${CDY}$((n-3))${CN}"
+	if [[ "$n" -gt 2 ]]; then
+		echo -e "Number of processes running: ${CDY}$((n-2))${CN}"
 		# Display the running processes
 		str="process is"
-		[[ "$n" -gt 4 ]] && str="processes are"
-		echo -e "${CY}WARNING: ${CR}$((n-3))${CY} ${str} still running:${CN}"
-		# exec_errnull docker exec "lg-${LID}" pgrep -v '^\[SF' -al | tail -n+3 | while read x; do echo -e "${CDY}--> ${CDG}${x:0:75}${CN}"; done
-		exec_errnull docker exec "lg-${LID}" pgrep -v '^\[SF' -al | tail -n+3 | while read x; do p="${x%% *}      "; n="${x#* }"; echo -e "${CDY}--> ${CDR}${p:0:8}${CDG}${n:0:68}${CN}"; done
+		[[ "$n" -gt 3 ]] && str="processes are"
+		echo -e "${CY}WARNING: ${CR}$((n-2))${CY} ${str} still running:${CN}"
+		exec_errnull docker exec "lg-${LID}" pgrep -v '^\[SF' -al | tail -n+2 | while read x; do p="${x%% *}      "; n="${x#* }"; echo -e "${CDY}--> ${CDR}${p:0:8}${CDG}${n:0:68}${CN}"; done
 		echo -e "\
 -------> The encrypted filesystem in /sec will remain accessible until
 -------> the last shell exits or all background processes terminate.
@@ -302,7 +319,7 @@ print_to_many_servers()
 {
 	echo >&2 -e "\
 [${CR}ERROR${CN}]
---> ${CDY}You ($YOURIP) have to many servers running${CN}
+--> ${CDY}You ($YOUR_IP) have to many servers running${CN}
 --> Read ${CB}${CUL}https://www.thc.org/segfault/youcheapfuck${CN}
 --> Contact us on Telegram: ${CW}https://t.me/thcorg${CN}"
 }
@@ -318,8 +335,17 @@ spawn_shell_exit()
 	# $@ is either ("-c", "<command>") or empty
 	DEBUGF "ARG(${#})=$*"
 
+	# Update current IP:
+	tofile "${YOUR_IP}" "/config/self-for-guest/lg-${LID}/ip"
+	tofile "${YOUR_GEOIP}" "/config/self-for-guest/lg-${LID}/geoip"
+
+	# Request a reverse Port Forward
+	[[ ! -f "/config/self-for-guest/lg-${LID}/reverse_ip" ]] && mk_portforward "${LID}"
+
+	# docker exec
 	docker-exec-sigproxy exec "$ARG" "lg-${LID}" nice -n"${SF_USER_NICE_SCORE:?}" zsh "${PARAM[@]}"
 	ret="$?" # save return value and exit this script later with same return value.
+	DEBUGF "Exited with $ret"
 	print_goodbye
 
 	exit "$ret"
@@ -347,10 +373,6 @@ setup_fs_limit()
 
 	# Backing FS must be of type XFS
 	[[ "$(docker info --format '{{json .DriverStatus}}' | jq -r '.[0][1]')" != "xfs" ]] && ERREXIT 1 "Backing FS is not XFS but SF_USER_ROOT_FS_LIMIT is set"
-
-	# Backing FS is of type XFS.
-	# Let's try if we can mount it with restrictions:
-	# docker run -it --storage-opt size=12m sf-gsnc true || return
 
 	DOCKER_ARGS+=("--storage-opt")
 	DOCKER_ARGS+=("size=${SF_USER_ROOT_FS_LIMIT:?}")
@@ -395,7 +417,7 @@ load_limits()
 # wait_for_conn_limit <ID> <ts_window>
 # Allow a max of 5 new connections within <ts_window>.
 # Give up after 120 seconds.
-#   ID - is either "all" for system wide limit or YOURIP_HASH for per IP limit
+#   ID - is either "all" for system wide limit or YOUR_IP_HASH for per IP limit
 wait_for_conn_limit()
 {
 	local ts_window
@@ -434,7 +456,7 @@ wait_for_conn_limit()
 wait_for_resources()
 {
 	# 5 Connections within 60 seconds from the same IP.
-	wait_for_conn_limit "${YOURIP_HASH}" "60" 
+	wait_for_conn_limit "${YOUR_IP_HASH}" "60" 
 	# 5 Connections within 15 seconds all in all
 	wait_for_conn_limit "all" "15"
 }
@@ -454,7 +476,7 @@ check_limit_server_by_ip()
 		exec_devnull docker container inspect "lg-${LID}" -f '{{.State.Status}}' && return
 	}
 
-	fn="/dev/shm/ip-${YOURIP_HASH}.conf"
+	fn="/dev/shm/ip-${YOUR_IP_HASH}.conf"
 
 	[[ -f "$fn" ]] && {
 		eval "$(grep ^ARR "$fn")"
@@ -482,11 +504,35 @@ check_limit_server_by_ip()
 			SF_USER_CPU_SHARE=2
 			SF_USER_OOM_SCORE=1000
 			SF_USER_NICE_SCORE=19
-			DEBUGF "${n}. server from ${YOURIP}. CPU_SHARE=${SF_USER_CPU_SHARE}, OOM=${SF_USER_OOM_SCORE}."
+			DEBUGF "${n}. server from ${YOUR_IP}. CPU_SHARE=${SF_USER_CPU_SHARE}, OOM=${SF_USER_OOM_SCORE}."
 		}
 	}
 
 	tofile "ARR=(${arr_new[*]} $LID)" "$fn"
+}
+
+# We must not request the guest's IP over the network (leakage). The best we can do is
+# lookup his IP in a local database.
+mk_geoip()
+{
+	local ip
+	ip=${1}
+	[[ ! -f /sf/share/GeoLite2-City.mmdb ]] && return
+
+	[[ -z ${ip} ]] && return
+
+	local city
+	local cc
+	res=$(mmdbinspect --db /sf/share/GeoLite2-City.mmdb "${ip}")
+	city=$(echo "$res" | jq -r '.[0].Records[0].Record.city.names.en | select(. != null)')
+	cc=$(echo "$res" | jq -r '.[0].Records[0].Record.country.iso_code | select(. != null)')
+
+	unset YOUR_GEOIP
+	if [[ -n $city && -n $cc ]]; then
+		YOUR_GEOIP+="${city}/${cc}"
+	elif [[ -n $city || -n $cc ]]; then
+		YOUR_GEOIP+="${city}${cc}"
+	fi
 }
 
 # Find out if SSHD spawns a shell or a command.
@@ -523,7 +569,10 @@ fi
 [[ -n $SF_DEBUG ]] && SF_DEBUG=1
 ### ----END SANITIZE----
 
-LID=$(echo -n "LID ${SF_SEC}" | sha512sum | base64 | tr -dc '[:alpha:]' | head -c 10)
+# LID=$(echo -n "LID ${SF_SEC}" | sha512sum | base64 | tr -dc '[:alpha:]' | head -c 10)
+LID=$(echo -n "LID ${SF_SEC}" | sha512sum | base64 -w0)
+LID="${LID//[^[:alpha:]]}"
+LID="${LID:0:10}"
 
 [[ -z $SF_SEED ]] && ERREXIT 244 "SF_SEED= is not set."
 MARKFILE="THIS-DIRECTORY-IS-NOT-ENCRYPTED--DO-NOT-USE.txt"
@@ -542,6 +591,8 @@ check_limit_server_by_ip
 [[ ! -f "${SF_SEC_DIR}/.IS-ENCRYPTED" ]] && ERREXIT 243 "System not ready yet (wrong EncFS password. Please inform the admin to set correct SF_SEED)"
 
 mk_hostname
+
+mk_geoip "${YOUE_IP}"
 
 HNLID_DIR="${SF_CONFIG_DIR}/db/hn"
 HNLID_FILE="${HNLID_DIR}/hn2lid-${SF_HOSTNAME}"
@@ -580,61 +631,21 @@ else
 	touch "${DB_DIR}/db-${LID}/created.txt" || ERREXIT
 	# exec_errnull date +%s >"${DB_DIR}/db-${LID}/created.txt" || ERREXIT
 	[[ -d "${HNLID_DIR}" ]] || exec_devnull mkdir "${HNLID_DIR}"
-	tofile "$LID" "${HNLID_FILE}"
+	tofile "$LID" "${HNLID_FILE}" || ERREXIT 231 "tofile: Failed to create hnlid_file"
 fi
 
 DEBUGF "LID=${LID} SF_HOSTNAME=${SF_HOSTNAME}"
 
-if [[ "$(exec_errnull docker container inspect "encfs-${LID}" -f '{{.State.Status}}')" != "running" ]]; then
-	LENCFS_PASS=$(echo -n "EncFS-PASS-${SF_SEED}${SF_SEC}" | sha512sum | base64 | tr -dc '[:alpha:]' | head -c 24)
-	[[ -z $LENCFS_PASS ]] && ERREXIT 241 "Failed to create session password"
-	# HERE: encfs is not already running for this instance...
-	DEBUGF "EncFS-${LID} is not yet running..."
-	# DEBUGF "Using 'EncFS-PASS-${SF_SEED:0:2}...${SF_SEC} => ${LENCFS_PASS}"
+# Create EncFS password
+encfspass=$(echo -n "EncFS-PASS-${SF_SEED}${SF_SEC}" | sha512sum | base64 -w0)
+encfspass="${encfspass//[^[:alpha:]]}"
+encfspass="${encfspass:0:24}"
+[[ -z $encfspass ]] && ERREXIT 241 "Failed to create session password"
 
-	# EncFS	to mount encrypted to mount-point.
-	# Run in background (-d)
-	# Use exec_devnull to redirect Container-ID to /dev/null (docker run -d).
-	exec_devnull docker run \
-		--oom-score-adj=500 \
-		--rm \
-		--name "encfs-${LID}" \
-		--cap-add SYS_ADMIN \
-		--device /dev/fuse \
-		--security-opt apparmor:unconfined \
-		--env LENCFS_PASS="${LENCFS_PASS}" \
-		--env LID="${LID}" \
-		--env SF_DEBUG="${SF_DEBUG}" \
-		--log-driver "${SF_DOCKER_LOG}" \
-		-v "${SF_BASEDIR}/data/user:/encfs/raw" \
-		-v "${SF_ENCFS_SEC_DIR}/user-${LID}:/encfs/sec:shared" \
-		-v "/var/run/docker.sock:/var/run/docker.sock" \
-		-d \
-		sf-encfs || ERREXIT 251 "Could not create /sec..."
-fi
-echo_pty -n ".."
-
-# Wait until sf-encf has mounted the secure drive...or otherwise this
-# will show an insecure directory:
-#    ssh user@segfault.thc.org "ls -al /sec"
-# This will loop until the MARKFILE is gone (e.g. encfs mounted a directory over it)
-# NOTE: It would be quicker to have /encfs/sec available in this sf-host instance
-#       but this may also pose a security risk: A vulnerability in SSHD would
-#       expose all encrypted drives. Doing it with 'docker run' means that
-#       the hacker would to to break docker - which is easy enough given that the
-#       docker-socket is available in this context but still a step harder.
-
-DEBUGF "Waiting until /sec becomes available..."
-docker exec \
-	"encfs-${LID}" \
-	/bin/sh -c \
-	"LID=\"${LID}\" \
-	SF_DEBUG=\"${SF_DEBUG}\" \
-	MARKFILE=\"${MARKFILE}\" \
-	/mount.sh" || ERREXIT 244 "Failed to set up /sec..."
-
-echo_pty -n ".."
-
+res=$(echo -e "RPUSH encfs \"${LID} ${encfspass} $$\"\n\
+BLPOP \"encfs-${LID}-$$\" 10" | REDISCLI_AUTH="${SF_REDIS_AUTH}" redis-cli --raw -h sf-redis) || ERREXIT 230 "Can't reach EncFSD"
+[[ -z $res || "${res##*$'\n'}" != "OK" ]] && ERREXIT 229 "Bad answer from EncFSD"
+echo_pty -n "...."
 
 # Attach to instance if already running
 [[ -n $IS_TRY_EXISTING ]] && {
@@ -653,24 +664,31 @@ echo_pty -n ".."
 ### Create ONION directory:
 # This script runs under UID=1000 (root) and does not have write permission to
 # /onion. Thus jump via docker.
-[[ ! -d "${SF_WWW_ROOT_DIR}" ]] && { 
-	DEBUGF "Creating /onion/${SF_HOSTNAME,,}"
-	if [[ -z $SF_EMU ]]; then
-		exec_devnull docker exec "sf-host${SF_HOST_CONTAINER_NAME_SUFFIX}" mkdir "${SF_WWW_ROOT_DIR}/${SF_HOSTNAME,,}"
-	else
-		mkdir "${SF_WWW_ROOT_DIR}/${SF_HOSTNAME,,}" || ERREXIT
-	fi
-}
+## NOTE: Not need because docker-run will create the mount point (-v forces creation)
+# [[ ! -d "${SF_WWW_ROOT_DIR}/${SF_HOSTNAME,,}" ]] && { 
+# 	DEBUGF "Creating /onion/${SF_HOSTNAME,,}"
+# 	if [[ -z $SF_EMU ]]; then
+# 		exec_devnull docker exec "sf-host${SF_HOST_CONTAINER_NAME_SUFFIX}" mkdir "${SF_WWW_ROOT_DIR}/${SF_HOSTNAME,,}"
+# 	else
+# 		mkdir "${SF_WWW_ROOT_DIR}/${SF_HOSTNAME,,}" || ERREXIT
+# 	fi
+# }
 
 # Starting GUEST shell
 # Challenge: Keep user processes running that got spawned in the background
 # even when first instance terminates. Also do not terminate instance
 # when there are still shells using it ('docker exec').
-# Solution: Spawn a docker in the background that monitors the number of
-# processes and use 'docker exec' for every connection.
+# Solution: Spawn a container in the background and always use 'docker exec' to
+# create a shell for the user.
 
-
+# SIGTERM is not delivered to PID==1.
+# Use --init so that 'docker stop lg-' works immediatly: Deliver SIGTERM to
+# process group. tiny-init notices the sigchld of died process and terminates
+# itself.
+# FIXME: Could write my own tiny-init that spawns itself, sleeps forever and
+# waits for child. Would save memory.
 ### Start the care taker...
+xmkdir "/config/self-for-guest/lg-${LID}"
 exec_devnull docker run \
 	--hostname "sf-${SF_HOSTNAME}" \
 	"${DOCKER_ARGS[@]}" \
@@ -678,7 +696,6 @@ exec_devnull docker run \
 	--init \
 	--ulimit nofile="${SF_ULIMIT_NOFILE}" \
 	--name "lg-${LID}" \
-	--init \
 	--cap-drop=MKNOD \
 	--net sf-guest \
 	--add-host tor:172.20.0.111 \
@@ -693,21 +710,21 @@ exec_devnull docker run \
 	--env SF_LID="${LID}" \
 	--env SF_IS_LOGINSHELL=1 \
 	--env SF_IS_GOLD_PROMPT="${SF_IS_GOLD_PROMPT}" \
-	-e SSH_CONNECTION \
 	--log-driver "${SF_DOCKER_LOG}" \
 	-v "${SF_CFG_GUEST_DIR:?}/:/config/guest:ro" \
+	-v "${SF_GUEST_SELFDIR:?}/lg-${LID}:/config/self:ro" \
 	-v "${SF_ENCFS_SEC_DIR}/user-${LID}:/sec:slave" \
 	-v "${SF_ENCFS_SEC_DIR}/everyone-root/everyone:/everyone:slave" \
 	-v "${SF_ENCFS_SEC_DIR}/www-root/www/${SF_HOSTNAME,,}:/onion:slave" \
 	-v "${SF_BASEDIR}/config/etc/sf/WARNING---SHARED-BETWEEN-ALL-SERVERS---README.txt:/everyone/WARNING---SHARED-BETWEEN-ALL-SERVERS---README.txt:ro" \
 	-d \
-	"sf-guest${SF_GUEST_CONTAINER_NAME_SUFFIX}" /sf/bin/sf-destructor.sh || ERREXIT 251 "Failed to set up guest instance..."
+	"sf-guest${SF_GUEST_CONTAINER_NAME_SUFFIX}" bash -c "exec -a \"[init-${LID}-${SF_HOSTNAME}]\" sleep infinity" || ERREXIT 251 "Failed to set up guest instance..."
 
 echo_pty -n ".."
 
 DEBUGF "Instance started..."
 
-# Wait for detached docker shell to become available...
+# Wait for detached docker shell to enter 'runnning' state
 n=0
 while :; do
 	str="$(exec_errnull docker container inspect "lg-${LID}" -f '{{.State.Status}}')"
