FobLiveonBeta

diff --git a/master/cgi-bin/rpc b/master/cgi-bin/rpc
--- a/master/cgi-bin/rpc
+++ b/master/cgi-bin/rpc
@@ -54,10 +54,12 @@ GetFormVars()
 		[[ ${key} == "verbose" ]] && IS_VERBOSE=1
 		[[ ${key} == "port" ]] && { val=$((${val//[^0-9]})); [[ $val -ge 32768 && $val -le 65535 ]] && R_PORT="$val"; }
 		[[ ${key} == "portsecret" ]] && R_PORTSECRET="${val//[^[:alnum:]]}"
-		[[ ${key} == "peerprivate" ]] && R_WT_PRIVATE="${val//[^[:alnum:]+\/]}="
+		[[ ${key} == "exit_private" ]] && R_WT_PRIVATE="${val//[^[:alnum:]+\/]}="
+		[[ ${key} == "exit_public" ]] && R_WT_PUBLIC="${val//[^[:alnum:]+\/]}="
 		[[ ${key} == "private" ]] && R_WG_PRIVATE="${val//[^[:alnum:]+\/]}="
 		[[ ${key} == "name" ]] && { val="${val//[^[:alnum:]]}"; R_WT_NAME="${val:0:13}"; }
 	done
+
 	IFS=$ifs
 }
 
@@ -83,58 +85,16 @@ GenSecret()
 	echo $str
 }
 
-cmd_net_list()
-{
-	local fn
-	local str
-	local name
-	local upstr
-
-	load_port
-	echo -en "\
-Port      : ${Y}$WG_PORT${N}
-Portsecret: ${Y}$PORTSECRET${N}
-"
-	ifaces=$(nsenter -t "$PID" -n wg show interfaces)
-	# List all configured names
-	echo -e "\
-
-Name           | Private (Peer)                               | Public
----------------+----------------------------------------------+---------------------------------------------"
-
-	for fn in "/config/db/db-${LID}/wg/wg-"*; do
-		[[ ! -f "$fn" ]] && break
-		str=$(basename "$fn")
-		name="${str#*-}"
-		[[ $fn != "/config/db/db-${LID}/wg/wg-${name}" ]] && continue # BAD
-		load_wt "$name"
-		load_wg "$name"
-		str="${name}                                      "
-		unset upstr
-		[[ $ifaces == *"wg${name}"* ]] && {
-			upstr="${G}"
-		}
-		echo -e "${upstr}${str:0:14}${N} | $WT_PRIVATE | $WG_PUBLIC"
-	done
-
-	exit
-}
-
-cmd_net_init_print_info()
+net_print_example()
 {
 	echo -en "\
-Port      : ${Y}$WG_PORT${N}
-Portsecret: ${Y}$PORTSECRET${N}
-Private   : ${Y}$WG_PRIVATE${N}
-Name      : ${Y}$WT_NAME${N}
-
-To connect with ${M}Wiretap${N} use this command on the remote host:
-    ${C}wiretap serve --private  ${WT_PRIVATE} \\
+To connect with ${M}Wiretap${N} use this command on the Exit Node:
+    ${C}wiretap serve --private  ${WT_PRIVATE:-<PrivateKey>} \\
                   --public   ${WG_PUBLIC} \\
                   --endpoint ${SF_FQDN}:${WG_PORT}${N}
-To connect with ${M}WireGuard${N} use this configuration on the remote host:${F}
+To connect with ${M}WireGuard${N} use this configuration on the Exit Node:${F}
 [Interface]
-PrivateKey = ${WT_PRIVATE}
+PrivateKey = ${WT_PRIVATE:-<PrivateKey>}
 Address = 192.168.0.2/32
 Address = fd::2/128
 
@@ -143,10 +103,74 @@ PublicKey = ${WG_PUBLIC}
 AllowedIPs = 0.0.0.0/0, ::/0
 EndPoint = ${SF_FQDN}:${WG_PORT}
 PersistentKeepalive = 25${N}
-
-Thereafter execute ${C}curl rpc/net/up -d name=${WT_NAME}${N} to exit via this peer.
 "
 }
+
+cmd_net_list()
+{
+	local fn
+	local str
+	local name
+	local upstr
+	local ex_wt_private
+	local ex_wg_public
+	local privstr
+
+	load_port
+	echo -en "\
+Port      : ${Y}$WG_PORT${N}
+Portsecret: ${Y}$PORTSECRET${N}
+"
+	ifaces="$(nsenter -t "$PID" -n wg show interfaces) "
+	# List all configured names
+	echo -e "\
+
+Name (${G}active${N})  |           | Private                                      | Public  
+---------------+-----------+----------------------------------------------+---------------------------------------------"
+
+	for fn in "${LID_WGDIR}/wg-"*; do
+		[[ ! -f "$fn" ]] && break
+		str=$(basename "$fn")
+		name="${str#*-}"
+		[[ $fn != "${LID_WGDIR}/wg-${name}" ]] && continue # BAD
+		# load_wt "$name"
+		load_wg "$name"
+		str="${name}                                      "
+		unset upstr
+		[[ $ifaces == *"wg${name} "* ]] && {
+			upstr="${G}"
+			ex_wt_private="$WT_PRIVATE"
+			ex_wg_public="$WG_PUBLIC"
+		}
+		privstr="${WT_PRIVATE:-                                                                            }"
+		echo -e "${upstr}${str:0:14}${N} | Server    | ${F}${WG_PRIVATE:0:10}##################################${N} | ${WG_PUBLIC}\n               | Exit Node | ${privstr:0:44} | ${F}$WT_PUBLIC${N}"
+	done
+
+	echo ""
+	[[ -z $WT_PUBLIC ]] && {
+		echo -e "${Y}WARNING${N}: No Exit Nodes configured. Use ${C}curl rpc/net/up${N} first."
+		exit
+	}
+
+	[[ -z $ex_wg_public ]] && {
+		echo -e "${Y}WARNING${N}: No interface is up. Use ${C}curl rpc/net/up -d name=<NAME>${N} first."
+		exit
+	}
+
+	net_print_example
+	exit
+}
+
+net_init_print_info()
+{
+	echo -e "\
+Port      : ${Y}$WG_PORT${N}
+Portsecret: ${Y}$PORTSECRET${N}
+Private   : ${Y}$WG_PRIVATE${N}
+Name      : ${Y}$WT_NAME${N}
+"
+}
+
 
 write_portfile()
 {
@@ -154,7 +178,7 @@ write_portfile()
 WG_PORT=\"${WG_PORT}\"
 ASSIGNED_LID=\"${LID}\"
 PORTSECRET=\"${PORTSECRET}\"
-" >"/config/db/db-${LID}/wg/port" || BAIL "Failed to store WireGuard Port."
+" >"${LID_WGDIR}/port" || BAIL "Failed to store WireGuard Port."
 
 	echo "WG_PORT=${WG_PORT}" >"/config/db/wg/sec2port-${PORTSECRET}"
 	# Link to LID:
@@ -170,26 +194,28 @@ write_wgfile()
 	echo -n "\
 WG_PRIVATE=\"${WG_PRIVATE}\"
 WG_PUBLIC=\"${WG_PUBLIC}\"
+WT_PRIVATE=\"${WT_PRIVATE}\"
+WT_PUBLIC=\"${WT_PUBLIC}\"
 WG_PORT=\"${WG_PORT}\"
-" >"/config/db/db-${LID}/wg/wg-${name}" || BAIL "Failed to store WG information."
+" >"${LID_WGDIR}/wg-${name}" || BAIL "Failed to store WG information."
 
 	ln -sf "../db-${LID}/wg/wg-${name}" "/config/db/wg/wg-${name}"
 }
 
 # [WT_NAME]
-write_wtfile()
-{
-	local name
-	name="$1"
+# write_wtfile()
+# {
+# 	local name
+# 	name="$1"
 
-	echo -n "\
-WT_PRIVATE=\"${WT_PRIVATE}\"
-WT_PUBLIC=\"${WT_PUBLIC}\"
-WG_PORT=\"${WG_PORT}\"
-" >"/config/db/db-${LID}/wg/wt-${name}" || BAIL "Failed to store WT information."
+# 	echo -n "\
+# WT_PRIVATE=\"${WT_PRIVATE}\"
+# WT_PUBLIC=\"${WT_PUBLIC}\"
+# WG_PORT=\"${WG_PORT}\"
+# " >"${LID_WGDIR}/wt-${name}" || BAIL "Failed to store WT information."
 
-	ln -sf "../db-${LID}/wg/wt-${name}" "/config/db/wg/wt-${name}"
-}
+# 	ln -sf "../db-${LID}/wg/wt-${name}" "/config/db/wg/wt-${name}"
+# }
 
 # Assign port to _this_ LID
 # [portsecret]
@@ -202,21 +228,27 @@ cmd_net_init_move()
 	source "/config/db/wg/sec2port-${psec}" 2>/dev/null || BAIL "Portsecret ${psec} is not known."
 	[[ ${ASSIGNED_LID} == $LID ]] && return # Already assigned to this LID
 	ln -sf "../db-${LID}/wg/port" "/config/db/wg/port-${WG_PORT}"
+	PORTSECRET="$1"
+	write_portfile
 }
 
 # rpc/net/init
 # Assign/Retrieve WireGuard port for this LID
-cmd_net_init()
+net_init()
 {
 	local n
 	local err
 	local arr
 
-	arr=($(echo /config/db/db-${LID}/wg/wt-*))
-	[[ ${#arr[@]} -gt 10 ]] && BAIL "${R}ERROR${N}: To many Peers. Delete some first." "${R}PEERS-MAX${N} " "Limit: ${#arr[@]}"
+	arr=($(echo "${LID_WGDIR}/wg-"*))
+	[[ ${#arr[@]} -gt 16 ]] && BAIL "${R}ERROR${N}: To many Peers. You must delete some first.
+Use ${C}curl rpc/net/list${N} to see them all.
+Use ${C}curl rpc/net/del -d name=<NAME>${N} to delete <NAME>.
+Use ${C}curl rpc/net/del -d name=all${N} to delete them all." "${R}PEERS-MAX${N} " "Limit: ${#arr[@]}"
 
 	[[ -n ${R_PORTSECRET} ]] && cmd_net_init_move "${R_PORTSECRET}"
-	if source "/config/db/db-${LID}/wg/port" 2>/dev/null; then
+
+	if source "${LID_WGDIR}/port" 2>/dev/null; then
 		# HERE: Port already assigned to this LID,
 		[[ -n ${R_PORT} ]] && [[ $R_PORT -ne $WG_PORT ]] && echo -e "${Y}WARNING:${N} Ignoring request for Port ${R_PORT}. Port already set to ${WG_PORT}."
 	else
@@ -240,45 +272,68 @@ Port ${R_PORT} is already in use. You can assign it to this server like so:\
 		fi
 	fi
 
-	PORTSECRET="${WG_PORT}_$(GenSecret)"
-	write_portfile
+	[[ -z $PORTSECRET ]] && {
+		PORTSECRET="${WG_PORT}_$(GenSecret)"
+		write_portfile
+	}
 
-	[[ -e "/config/db/wg/wt-${R_WT_NAME}" ]] && {
-		WT_NAME=${R_WT_NAME}
+	[[ -e "/config/db/wg/wg-${R_WT_NAME}" ]] && {
 		echo -e "${R}ERROR${N}: '$R_WT_NAME' already exists. Delete it first with ${C}curl rpc/net/del -d name=${R_WT_NAME}${N}"
-		load_wt "${R_WT_NAME}"
-		load_wg "${R_WT_NAME}"
-		cmd_net_init_print_info
+		# load_wt "${R_WT_NAME}"
+		# load_wg "${R_WT_NAME}"
+		# WT_NAME=${R_WT_NAME}
+		# net_init_print_info
+		# net_print_example
 		exit
 	}
 
-	[[ -n $R_WT_PRIVATE ]] && WT_PRIVATE=$R_WT_PRIVATE || WT_PRIVATE=$(wg genkey)
-	WT_PUBLIC=$(echo "$WT_PRIVATE" | wg pubkey)
-	[[ -n $R_WT_NAME ]] && WT_NAME="${R_WT_NAME}" || { val="${WT_PUBLIC//[^[:alnum:]]}"; WT_NAME="${val:0:4}"; }
-	write_wtfile "${WT_NAME}"
+	# We do not need the peer's private key but it is more convenient
+	# to the user to show him one complete ./wiretap command line.
+	if [[ -z $R_WT_PRIVATE ]]; then
+		if [[ -z $R_WT_PUBLIC ]]; then
+			# No PRIVATE and No PUBLIC. User wants us
+			# to generate PUBLIC key (and for this we generate private)
+			WT_PRIVATE=$(wg genkey)
+		fi
+		# WT_PRIVATE can be empty (The Exit Node's private does not need to be known)
+	else
+		WT_PRIVATE="$R_WT_PRIVATE"
+	fi
 
-	WG_PRIVATE=$(wg genkey)
+	[[ -n $R_WT_PUBLIC ]] && WT_PUBLIC="$R_WT_PUBLIC" || WT_PUBLIC=$(echo "$WT_PRIVATE" | wg pubkey)
+
+	[[ -n $R_WT_NAME ]] && WT_NAME="${R_WT_NAME}" || { val="${WT_PUBLIC//[^[:alnum:]]}"; WT_NAME="${val:0:4}"; }
+	# write_wtfile "${WT_NAME}"
+
+	# Generate server's private unless it's provided by user
+	[[ -n $R_WG_PRIVATE ]] && WG_PRIVATE="$R_WG_PRIVATE" || WG_PRIVATE=$(wg genkey)
 	WG_PUBLIC=$(echo "$WG_PRIVATE" | wg pubkey)
 	write_wgfile "${WT_NAME}"
+}
 
-	cmd_net_init_print_info
+cmd_net_init()
+{
+	net_init
+	net_init_print_info
+	# net_print_example
+	echo -e "Use ${C}curl rpc/net/up -d name=${WT_NAME}${N} to connect an Exit Node."
 
 	exit
 }
 
 load_port()
 {
-	source "/config/db/db-${LID}/wg/port" 2>/dev/null || BAIL "${R}ERROR${N}: No port found. Use ${C}curl rpc/net/init${N} first."
+	source "${LID_WGDIR}/port" 2>/dev/null || BAIL "${R}ERROR${N}: No port found. Use ${C}curl rpc/net/init${N} first."
 }
 
-load_wt()
-{
-	source "/config/db/db-${LID}/wg/wt-${1}" || BAIL "Not found: ${1}. Try ${C}curl rpc/net/init -d name=${1}${N}" "ERROR: " "Not found: db-${LID}/wg/wt-${1}"
-}
+# load_wt()
+# {
+# 	source "${LID_WGDIR}/wt-${1}" || BAIL "Not found: ${1}. Try ${C}curl rpc/net/init -d name=${1}${N}" "ERROR: " "Not found: wg/wt-${1}"
+# }
 
 load_wg()
 {
-	source "/config/db/db-${LID}/wg/wg-${1}" || BAIL "Not found." "ERROR: " "Not found: db-${LID}/wg/wg-${1}"
+	source "${LID_WGDIR}/wg-${1}" || BAIL "Not found." "ERROR: " "Not found: wg/wg-${1}"
 }
 
 
@@ -318,30 +373,28 @@ cmd_net_del()
 	load_port
 	local fn
 
-	[[ -z $R_WT_NAME ]] && BAIL "Use ${C}-d name=<name>${N}"
+	[[ -z $R_WT_NAME ]] && BAIL "Use ${C}-d name=<NAME|all>${N}"
 
 	net_down "$R_WT_NAME"
 	if [[ "$R_WT_NAME" == "all" ]]; then
-		# Delete PORT assignment
-		xrm "/config/db/wg/sec2port-${PORTSECRET}" "/config/db/wg/port-${WG_PORT}" "/config/db/db-${LID}/wg/port"
-
 		# Delete all private keys
-		for fn in "/config/db/db-${LID}/wg/wg-"*; do
+		for fn in "${LID_WGDIR}/wg-"*; do
 			[[ ! -f "$fn" ]] && break
 			str=$(basename "$fn")
 			name="${str#*-}"
-			[[ $fn != "/config/db/db-${LID}/wg/wg-${name}" ]] && continue # BAD
+			[[ $fn != "${LID_WGDIR}/wg-${name}" ]] && continue # BAD
 			# Delete all links
-			xrm "/config/db/wg/wg-${name}" "/config/db/wg/wt-${name}"
+			# xrm "/config/db/wg/wg-${name}" "/config/db/wg/wt-${name}"
+			# xrm  "${LID_WGDIR}/wg-${name}"  "${LID_WGDIR}/wt-${name}"
+			xrm "/config/db/wg/wg-${name}" "${LID_WGDIR}/wg-${name}"
 		done
-		rm -rf "/config/db/db-${LID}/wg"
 		echo -en "All private keys deleted."
 		exit
 	fi
 
-	[[ ! -f "/config/db/db-${LID}/wg/wg-${R_WT_NAME}" ]] && BAIL "${R}Not found${N}: ${R_WT_NAME}"
-	xrm "/config/db/wg/wg-${R_WT_NAME}" "/config/db/db-${LID}/wg/wg-${R_WT_NAME}"
-	xrm "/config/db/wg/wt-${R_WT_NAME}" "/config/db/db-${LID}/wg/wt-${R_WT_NAME}"
+	[[ ! -f "${LID_WGDIR}/wg-${R_WT_NAME}" ]] && BAIL "${R}Not found${N}: ${R_WT_NAME}"
+	xrm "/config/db/wg/wg-${R_WT_NAME}" "${LID_WGDIR}/wg-${R_WT_NAME}"
+	# xrm "/config/db/wg/wt-${R_WT_NAME}" "${LID_WGDIR}/wt-${R_WT_NAME}"
 
 	echo -en "\
 ${G}Private key deleted${N} ($R_WT_NAME).
@@ -360,19 +413,31 @@ cmd_net()
 cmd_net_show()
 {
 	local str
+	local dev
+	local exe
+
+	dev="all"
+	[[ -n $R_WT_NAME ]] && dev="wg${R_WT_NAME}"
 
 	unset IFS
 	if [[ -z $COLOR ]]; then
-		str=$(nsenter -t "${PID}" -n wg show)
+		str=$(nsenter -t "${PID}" -n wg show "${dev}")
 	else
 		# Use 'script' to force color output
-		str=$(script -q -c "nsenter -t \"${PID}\" -n wg show" /dev/null </dev/null)
+		str=$(script -q -c "nsenter -t \"${PID}\" -n wg show \"${dev}\"" /dev/null </dev/null)
 	fi
-	[[ -n $str ]] && { echo "$str"; exit; }
+	[[ -n $str ]] && {
+		echo "$str"
+		[[ "$str" != *"latest handshake"* ]] && {
+			echo -e "\n${Y}WARNING${N}: EXIT NODE NOT CONNECTED.\nDid you forget to start Wiretap/WireGuard on the Exit Node?"
+		}
+		exit
+	}
 
 	echo -e "\
-No Peer connected. To connect a peer:
-    ${C}curl rpc/net/up -d name=<NAME>${N}"
+No interface connected.
+Use ${C}curl rpc/net/list${N} to list all Exit Nodes.
+Use ${C}curl rpc/net/up -d name=<NAME>${N} to connect to an Exit Node."
 
 	exit
 }
@@ -388,21 +453,36 @@ cmd_net_down()
 cmd_net_help()
 {
 	echo -en "\
-Create new peer : ${C}curl rpc/net/init -d name=<NAME>${N}
-Delete peer     : ${C}curl rpc/net/del  -d name=<NAME>${N}
-List peers      : ${C}curl rpc/net/list${N}
-Show connections: ${C}curl rpc/net/show${N}
-Move port to a new server:
+Create Exit Node : ${C}curl rpc/net/init [-d name=<NAME>] [-d private=<PrivateKey>]
+                                     [-d exit_public=<PublicKey>]
+                                     [-d exit_private=<PrivateKey>]${N}
+Delete Exit Node : ${C}curl rpc/net/del  -d name=<NAME|all>${N}
+List Exit Nodes  : ${C}curl rpc/net/list${N}
+Show connections : ${C}curl rpc/net/show${N}
+Move port to a different Root Server:
     ${C}curl rpc/net/init -d portsecret=<portsecret>${N}
-Connect a peer:
+Connect Exit Node:
     ${C}curl rpc/net/up -d name=<NAME>${N}
-Disconnect a peer:
-    ${C}curl rpc/net/down -d name=<NAME>${N}
+    (and any parameters from rpc/net/init)
+Disconnect Exit Node:
+    ${C}curl rpc/net/down [-d name=<NAME>]${N}
 "
 
 	exit
 }
 
+CheckGoodKey()
+{
+	local key
+	local opt
+
+	key=$1
+	opt=$2
+
+	[[ -z $key ]] && return
+	[[ ${#key} -eq 44 ]] && return
+	BAIL "${R}ERROR${N}: Bad Key for ${opt}="
+}
 
 0<&- # Close STDIN
 Sanitize
@@ -417,6 +497,12 @@ GetFormVars
 	N=$CN
 	F=$CF
 }
+
+CheckGoodKey "$R_WG_PRIVATE" "--private"
+CheckGoodKey "$R_WT_PRIVATE" "--exit_private"
+CheckGoodKey "$R_WT_PUBLIC"  "--exit_public"
+
+[[ -n $R_WT_PRIVATE ]] && [[ -n $R_WT_PUBLIC ]] && BAIL "${R}ERROR${N}: Set either PRIVATE or PUBLIC but not both."
 
 # Split into arguments
 _IFS=$IFS
@@ -451,7 +537,8 @@ IFS=$_IFS
 	arr=($(redr GET "ip:${REMOTE_ADDR}")) || BAIL "Bad Value" "Bad Value: " "ret=$?, ${#arr[@]}"
 	[[ ${#arr[@]} -ne 3 ]] && BAIL "Value != 3" "Value != 3: " "${#arr[@]}"
 	LID="${arr[0]}"
-	[[ ! -d "/config/db/db-${LID}/wg" ]] && mkdir "/config/db/db-${LID}/wg"
+	LID_WGDIR="/config/db/db-${LID}/wg"
+	[[ ! -d "${LID_WGDIR}" ]] && mkdir "${LID_WGDIR}"
 	# CID="${arr[1]}"
 	PID="${arr[2]}"
 
@@ -470,31 +557,46 @@ IFS=$_IFS
 	# NOT 'up' -> EXIT
 	[[ ${ARGS[1]} != 'up' ]] && { echo -e "${R}ERROR${N}: Unknown command."; cmd_net_help; }
 
-	[[ -z $R_WT_NAME ]] && BAIL "${R}ERROR:${N} Use ${C}curl rpc/net/up -d name=<Name>${N}."
 	WT_NAME="$R_WT_NAME"
+
+	[[ -z $WT_NAME ]] || [[ ! -f "${LID_WGDIR}/wg-${WT_NAME}" ]] && {
+		# R_WT_NAME not supplied _or_ R_WT_NAME does not exist => Create new one.
+		net_init
+		net_init_print_info
+	}
 	load_port
-	load_wt "${WT_NAME}"
+	# load_wt "${WT_NAME}"
 	load_wg "${WT_NAME}"
 
 	dev="wg${WT_NAME}"
 
 	load_config
 
-	# Delete old interface in either namespace:
+	# Delete interface in WG namespace (should never happen):
 	nsenter -t "${WG_PID}" -n ip link del "${dev}" 2>/dev/null
-	nsenter -t "${PID}" -n ip link del "${dev}" 2>/dev/null
 
-	err=$(nsenter -t "${WG_PID}" -n ip link add "${dev}" type wireguard 2>&1) || BAIL "Failed: ip link add $dev ($err)." "Failed $dev" ": $err"
-	nsenter -t "${WG_PID}" -n ip link set "${dev}" group 31337 || BAIL "FAIL"
+	# Delete all interface. Only allow ONE WG interface at a time.
+	# WireGuard only supports 1 private key per port number. Sharing the same
+	# private key among Exit Nodes wont work either as WG enforces a strict
+	# Routing Policy where no two WG interfaces can route 0.0.0.0/0.
+	# The only way around is to use different ports (and if we go down this route
+	# then it would be easier to implement WireGuard Port Multiplexer simiar to
+	# https://github.com/apernet/mwgp but use IPTABLES (NFQUEUE) instaed to make it
+	# _far_ more efficient.)
+	nsenter -t "${PID}" -n ip link delete group 31337 2>/dev/null
+	# nsenter -t "${PID}" -n ip link del "${dev}" 2>/dev/null
+
+	err=$(nsenter -t "${WG_PID}" -n ip link add "${dev}" type wireguard 2>&1) || BAIL "${R}ERROR${N}: Failed: ip link add $dev (${err:0:32})." "Failed $dev" ": $err"
+	nsenter -t "${WG_PID}" -n ip link set "${dev}" group 31337 || BAIL "${R}ERROR${N}: ip link set FAILED."
 	echo "$WG_PRIVATE" >/dev/shm/private.$$
-	nsenter -t "${WG_PID}" -n wg set "${dev}" listen-port "${WG_PORT}" private-key "/dev/shm/private.$$" peer "${WT_PUBLIC}" allowed-ips 0.0.0.0/0 || BAIL "Failed: wg set"
+	err=$(nsenter -t "${WG_PID}" -n wg set "${dev}" listen-port "${WG_PORT}" private-key "/dev/shm/private.$$" peer "${WT_PUBLIC}" allowed-ips 0.0.0.0/0 2>&1) || BAIL "${R}ERROR${N}: Failed: wg set (${err:0:128})"
 	rm -f /dev/shm/private.$$
 	# Move Interface to user's container:
-	err=$(nsenter -t "${WG_PID}" -n ip link set "${dev}" netns "${PID}" 2>&1) || BAIL "Failed to move $dev." "Failed $dev netns $PID" ": $err"
+	err=$(nsenter -t "${WG_PID}" -n ip link set "${dev}" netns "${PID}" 2>&1) || BAIL "${R}ERROR${N}: Failed to move $dev." "Failed $dev netns $PID" ": $err"
 
 	# Configure interface after moving
 	nsenter -t "${PID}" -n ip -4 address add 192.168.0.2/32 dev "${dev}"
-	err=$(nsenter -t "${PID}" -n ip -6 address add fd::2/128 dev "${dev}" 2>&1) || echo >&2 "ip -6: $err"
+	err=$(nsenter -t "${PID}" -n ip -6 address add fd::2/128 dev "${dev}" 2>&1) || echo >&2 "${CR}ERROR${CN}: ip -6: $err"
 	nsenter -t "${PID}" -n ip link set mtu 1420 up dev "${dev}"
 
 	# Add static routes for RPC
@@ -505,7 +607,13 @@ IFS=$_IFS
 
 	# nsenter -t "${PID}" -n ip --color=${COLOR:-never} addr show "${dev}"
 
-	echo -e "${G}SUCCESS${N}: All traffic is now routed via ${WT_NAME}."
+	echo -e "${G}SUCCESS${N}"
+	net_print_example
+
+	echo "---"
+	echo -e "Use ${C}curl rpc/net/down -d name=${WT_NAME}${N} to disconnect."
+	echo -e "Use ${C}curl rpc/net/del  -d name=${WT_NAME}${N} to delete the keys."
+	echo -e "Use ${Y}curl rpc/net/show${N} to check when the Exit Node '${WT_NAME}' has connected."
 
 	exit
 }
