more

diff --git a/master/cgi-bin/rpc b/master/cgi-bin/rpc
--- a/master/cgi-bin/rpc
+++ b/master/cgi-bin/rpc
@@ -121,7 +121,7 @@ cmd_net_list()
 Port      : ${Y}$WG_PORT${N}
 Portsecret: ${Y}$PORTSECRET${N}
 "
-	ifaces="$(nsenter -t "$PID" -n wg show interfaces) "
+	ifaces="$(nsenter.u1000 --setuid 0 --setgid 0 -t "$PID" -n wg show interfaces) "
 	# List all configured names
 	echo -e "\
 
@@ -182,7 +182,7 @@ PORTSECRET=\"${PORTSECRET}\"
 
 	echo "WG_PORT=${WG_PORT}" >"/config/db/wg/sec2port-${PORTSECRET}"
 	# Link to LID:
-	ln -sf "../db-${LID}/wg/port" "/config/db/wg/port-${WG_PORT}"
+	ln -sf "../user/lg-${LID}/wg/port" "/config/db/wg/port-${WG_PORT}"
 }
 
 # [WT_NAME]
@@ -199,23 +199,8 @@ WT_PUBLIC=\"${WT_PUBLIC}\"
 WG_PORT=\"${WG_PORT}\"
 " >"${LID_WGDIR}/wg-${name}" || BAIL "Failed to store WG information."
 
-	ln -sf "../db-${LID}/wg/wg-${name}" "/config/db/wg/wg-${name}"
+	ln -sf "../user/lg-${LID}/wg/wg-${name}" "/config/db/wg/wg-${name}"
 }
-
-# [WT_NAME]
-# write_wtfile()
-# {
-# 	local name
-# 	name="$1"
-
-# 	echo -n "\
-# WT_PRIVATE=\"${WT_PRIVATE}\"
-# WT_PUBLIC=\"${WT_PUBLIC}\"
-# WG_PORT=\"${WG_PORT}\"
-# " >"${LID_WGDIR}/wt-${name}" || BAIL "Failed to store WT information."
-
-# 	ln -sf "../db-${LID}/wg/wt-${name}" "/config/db/wg/wt-${name}"
-# }
 
 # Assign port to _this_ LID
 # [portsecret]
@@ -227,7 +212,7 @@ cmd_net_init_move()
 
 	source "/config/db/wg/sec2port-${psec}" 2>/dev/null || BAIL "Portsecret ${psec} is not known."
 	[[ ${ASSIGNED_LID} == $LID ]] && return # Already assigned to this LID
-	ln -sf "../db-${LID}/wg/port" "/config/db/wg/port-${WG_PORT}"
+	ln -sf "../user/lg-${LID}/wg/port" "/config/db/wg/port-${WG_PORT}"
 	PORTSECRET="$1"
 	write_portfile
 }
@@ -358,14 +343,14 @@ net_down()
 
 	# Shut down WG interface
 	if [[ -z $name || $name == "all" ]]; then
-		nsenter -t "${PID}" -n ip link delete group 31337
+		nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link delete group 31337
 	else
 		# Return early if device did not exist.
-		nsenter -t "${PID}" -n ip link delete "wg${name}" || return
+		nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link delete "wg${name}" || return
 	fi
 	# Restore default routing
 	echo -e "${Y}WARNING${N}: All traffic exits via the DEFAULT ROUTE now."
-	nsenter -t "${PID}" -n ip route add default via "${SF_NET_LG_ROUTER_IP}"
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add default via "${SF_NET_LG_ROUTER_IP}"
 }
 
 cmd_net_del()
@@ -421,10 +406,10 @@ cmd_net_show()
 
 	unset IFS
 	if [[ -z $COLOR ]]; then
-		str=$(nsenter -t "${PID}" -n wg show "${dev}")
+		str=$(nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n wg show "${dev}")
 	else
 		# Use 'script' to force color output
-		str=$(script -q -c "nsenter -t \"${PID}\" -n wg show \"${dev}\"" /dev/null </dev/null)
+		str=$(script -q -c "nsenter.u1000 --setuid 0 --setgid 0 -t \"${PID}\" -n wg show \"${dev}\"" /dev/null </dev/null)
 	fi
 	[[ -n $str ]] && {
 		echo "$str"
@@ -537,7 +522,7 @@ IFS=$_IFS
 	arr=($(redr GET "ip:${REMOTE_ADDR}")) || BAIL "Bad Value" "Bad Value: " "ret=$?, ${#arr[@]}"
 	[[ ${#arr[@]} -ne 3 ]] && BAIL "Value != 3" "Value != 3: " "${#arr[@]}"
 	LID="${arr[0]}"
-	LID_WGDIR="/config/db/db-${LID}/wg"
+	LID_WGDIR="/config/db/user/lg-${LID}/wg"
 	[[ ! -d "${LID_WGDIR}" ]] && mkdir "${LID_WGDIR}"
 	# CID="${arr[1]}"
 	PID="${arr[2]}"
@@ -583,8 +568,7 @@ IFS=$_IFS
 	# then it would be easier to implement WireGuard Port Multiplexer simiar to
 	# https://github.com/apernet/mwgp but use IPTABLES (NFQUEUE) instaed to make it
 	# _far_ more efficient.)
-	nsenter -t "${PID}" -n ip link delete group 31337 2>/dev/null
-	# nsenter -t "${PID}" -n ip link del "${dev}" 2>/dev/null
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link delete group 31337 2>/dev/null
 
 	err=$(nsenter -t "${WG_PID}" -n ip link add "${dev}" type wireguard 2>&1) || BAIL "${R}ERROR${N}: Failed: ip link add $dev (${err:0:32})." "Failed $dev" ": $err"
 	nsenter -t "${WG_PID}" -n ip link set "${dev}" group 31337 || BAIL "${R}ERROR${N}: ip link set FAILED."
@@ -595,17 +579,17 @@ IFS=$_IFS
 	err=$(nsenter -t "${WG_PID}" -n ip link set "${dev}" netns "${PID}" 2>&1) || BAIL "${R}ERROR${N}: Failed to move $dev." "Failed $dev netns $PID" ": $err"
 
 	# Configure interface after moving
-	nsenter -t "${PID}" -n ip -4 address add 192.168.0.2/32 dev "${dev}"
-	err=$(nsenter -t "${PID}" -n ip -6 address add fd::2/128 dev "${dev}" 2>&1) || echo >&2 "${CR}ERROR${CN}: ip -6: $err"
-	nsenter -t "${PID}" -n ip link set mtu 1420 up dev "${dev}"
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -4 address add 192.168.0.2/32 dev "${dev}"
+	err=$(nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip -6 address add fd::2/128 dev "${dev}" 2>&1) || echo >&2 "${CR}ERROR${CN}: ip -6: $err"
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip link set mtu 1420 up dev "${dev}"
 
 	# Add static routes for RPC
-	# nsenter -t "${PID}" -n ip route add "${RPC_IP}/32" dev eth0 # NOT NEEDED: RPC is on same network
-	nsenter -t "${PID}" -n ip route add "${SF_DNS}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
-	nsenter -t "${PID}" -n ip route del default 2>/dev/null
-	nsenter -t "${PID}" -n ip route add default dev "${dev}"
-
-	# nsenter -t "${PID}" -n ip --color=${COLOR:-never} addr show "${dev}"
+	# nsenter -t "${PID}" -n ip route add "${SF_PC_IP}/32" dev eth0 # NOT NEEDED: RPC is on same network
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add "${SF_TOR_IP}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add "${SF_NET_ONION}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add "${SF_DNS}" via "${SF_NET_LG_ROUTER_IP}" 2>/dev/null
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route del default 2>/dev/null
+	nsenter.u1000 --setuid 0 --setgid 0 -t "${PID}" -n ip route add default dev "${dev}"
 
 	echo -e "${G}SUCCESS${N}"
 	net_print_example
diff --git a/sfbin/sf b/sfbin/sf
--- a/sfbin/sf
+++ b/sfbin/sf
@@ -107,6 +107,7 @@ warn_file()
 
 load_env
 [[ -z $SF_DATADIR ]] && SF_DATADIR="${SF_BASEDIR}/data"
+[[ -z $SF_SHMDIR ]] && SF_SHMDIR="/dev/shm/sf"
 
 [[ ! -d "${SF_DATADIR}/user" ]] && mkdir -p "${SF_DATADIR}/user"
 [[ ! -d "${SF_DATADIR}/share" ]] && mkdir -p "${SF_DATADIR}/share"
@@ -150,18 +151,67 @@ blockio_init
 sysctl -q -w net.ipv4.neigh.default.gc_thresh3=65536 || WARN "Could not set /proc/.../gc_thresh3"
 sysctl -q -w net.netfilter.nf_conntrack_buckets=16384 || WARN "Could not set /proc/.../nf_conntrack_buckets"
 sysctl -q -w net.netfilter.nf_conntrack_max=131072 || WARN "Could not set /proc/.../nf_conntrack_max"
+# Each Hugepagesize is 2MB (grep HUGE /proc/meminfo)
+#  512 => 1g as HUGE 
+# 8192 => 16g as HUGE
+[[ ! $(cat /proc/sys/vm/nr_hugepages) -gt 0 ]] && WARN 'Huge Tables not set. Consider `echo "vm.nr_hugepages=8192" >>/etc/sysctl.conf && sysctl -w vm.nr_hugepages=8192`'
 
 warn_file "${SF_BASEDIR}/config/etc/nginx/nginx-rpc.conf"
 warn_file "${SF_BASEDIR}/config/etc/nginx/nginx.conf"
 warn_file "${SF_BASEDIR}/config/etc/sf/sf.conf"
 
-# STOP HERE: Check if there are any fils in /sf/sfbin that are not equal to ./sfbin
+# Check if there are any fils in /sf/sfbin that are not equal to ./sfbin
+for x in "${BINDIR}/"*; do
+	[[ ! -e "$x" ]] && WARN "Oops. Files missing in ${BINDIR}/*???"
+	str=$(md5sum "$x")
+	src=${str%% *}
+	x=$(basename "$x")
+	str=$(md5sum "${SF_BASEDIR}/sfbin/${x}" 2>/dev/null)
+	dst=${str%% *}
+	[[ $src != $dst ]] && WARN "${SF_BASEDIR}/sfbin/${x} is outdated. Please update with ${CDC}${BINDIR}/${x}${CN}"
+done
+
 
 # Make sure /dev/shm is 'shared'
 [[ "$(findmnt -no TARGET,PROPAGATION /dev/shm)" != *"shared"* ]] && {
 	mount --make-shared /dev/shm/ || ERREXIT 252
 }
 
+systemctl start sf.slice || WARN 'Could not start sf.slice'
+systemctl start sf-guest.slice || WARN 'Could not start sf-guest.slice'
+systemctl status sf.slice | grep Segfault >/dev/null || WARN 'Bad start sf.slice. Does not belong to Segfault.'
+systemctl status sf-guest.slice | grep Segfault >/dev/null || WARN 'Bad start sf-guest.slice. Does not belong to Segfault.'
+
+SF_CG_DIR="/sys/fs/cgroup"
+[[ -d "/sys/fs/cgroup/unified" ]] && {
+	SF_CG_DIR="/sys/fs/cgroup/unified"
+	# for cgroupv1 docker-run expects the absolute hierarchy path (for --cgroup-parent):
+	export SF_CG_PARENT="sf.slice/sf-guest.slice"
+}
+
+str=$(mount | grep ^cgroup2 | grep -F "$SF_CG_DIR" )
+[[ $str == *'nsdelegate'* ]] && {
+	# HERE: cgroup2 is in use.
+	echo -e >&2 "[$(date '+%F %T' -u)] [${CDY}WARN${CN}] ${SF_CG_DIR} is mounted with nsdelegate. Disabling nsdelegate."
+	str=${str##*\(}
+	str=${str%\)*}
+	# We need to move encfsd to the user's cgroup: From sf.slice (sf-encfsd) to sf.slice/sf-guest.slice.
+	# We need to turn of "nsdelegate" as otherwise there is no (?) way moving it.
+	# (write() to cgroup.procs returns ENOENT if nsdelegate is enabled.)
+
+	# There is no 'nonsdelegate' and removing nsdelegate requires a hack:
+	#   mount -t cgroup2 none /mnt && umount /mnt
+	#   mount -o remount,rw,nosuid,nodev,noexec,relatime,memory_recursiveprot /sys/fs/cgroup
+	# Test with:
+	#   docker run --rm -v /sys/fs/cgroup:/sys/fs/cgroup -it ubuntu bash -c 'sleep 31339 & echo $! >/sys/fs/cgroup/sf.slice/sf-guest.slice/docker-ANY-RUNNING-CONTAINER-ID-HERE.scope/cgroup.procs && echo $! OK'
+	mount -t cgroup2 none /mnt
+	umount /mnt
+	str="${str/,nsdelegate/}"
+	str="${str/nsdelegate,/}"
+	mount -o "remount,${str}" "${SF_CG_DIR}" || ERREXIT 255
+}
+
+grep -F sf.slice /etc/docker/daemon.json &>/dev/null && WARN "Obsolete sf.slice found in /etc/docker/daemon.json. Remove that line."
 # If there was a warning then wait...
 WARN_ENTER
 
